name: Build and Push Go Frontend Docker Image

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'  # Ajuste conforme necessário

      - name: Build Go application
        run: go build -o app .

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        run: |
          
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/gregorian-app:v-${{ github.event.pull_request.number }} -f build/Dockerfile .
          docker push $IMAGE

      - name: Atualizar a tag "latest"
        run: |
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/gregorian-app:v-${{ github.event.pull_request.number }} guiflauzino18/gregorian-app:latest
          docker push guiflauzino18/gregorian-app:latest
